<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <configSections>
        <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="TestClient.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
  <system.serviceModel>
    <bindings>
      <netTcpBinding>
        <binding name="defaultBinding"
                 openTimeout="00:10:00"
                 closeTimeout="00:10:00"
                 sendTimeout="00:10:00"
                 receiveTimeout="00:10:00">
          <security mode="None" />
        </binding>


      </netTcpBinding>
    </bindings>
    <client>
      <endpoint address="net.tcp://localhost:11233/TestService" binding="netTcpBinding"
          bindingConfiguration="defaultBinding" contract="TestService.ITestService"
          name="NetTcpBinding_ITestService">
        <identity>
          <dns value="localhost" />
        </identity>
      </endpoint>
    </client>
  </system.serviceModel>
  <applicationSettings>
    <TestClient.Properties.Settings>
      <setting name="NumberOfCalls" serializeAs="String">
        <value>20000</value>
      </setting>
      <setting name="IncludeExceptions" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="RetryFailures" serializeAs="String">
        <value>True</value>
      </setting>
    </TestClient.Properties.Settings>
  </applicationSettings>
</configuration>